import { Transaction, User } from "@/types";

export const sidebarLinks = [
  {
    imgURL: "/dashboard.svg",
    route: "/dashboard",
    label: "Dashboard",
  },
  {
    imgURL: "/loanservice.svg",
    route: "/loanservice",
    label: "Loan Services",
  },
  {
    imgURL: "/transaction.svg",
    route: "/transaction",
    label: "Transaction History",
  },
  {
    imgURL: "/transfer.svg",
    route: "/transfer",
    label: "Transfer Funds",
  },
  {
    imgURL: "/icons/connect-bank.svg",
    route: "/cards",
    label: "Cards",
  },
];

export const topCategoryStyles = {
  deposit: {
    bg: "bg-blue-25",
    circleBg: "bg-blue-100",
    text: {
      main: "text-blue-900",
      count: "text-blue-700",
    },
    progress: {
      bg: "bg-blue-100",
      indicator: "bg-blue-700",
    },
    icon: "/icons/monitor.svg",
  },
  withdrawal: {
    bg: "bg-success-25",
    circleBg: "bg-success-100",
    text: {
      main: "text-success-900",
      count: "text-success-700",
    },
    progress: {
      bg: "bg-blue-100",
      indicator: "bg-success-700",
    },
    icon: "/icons/coins.svg",
  },
  default: {
    bg: "bg-pink-25",
    circleBg: "bg-pink-100",
    text: {
      main: "text-pink-900",
      count: "text-pink-700",
    },
    progress: {
      bg: "bg-pink-100",
      indicator: "bg-pink-700",
    },
    icon: "/icons/shopping-bag.svg",
  },
};

export const accountData: User = {
  _id: "64a1b5d1a2b4c3d5e6f7a8c9",
  firstName: "John",
  lastName: "Doe",
  email: "johndoe@example.com",
  accountNumber: "123456789",
  balance: 1000.5,
  currency: "USD",
  role: "user",
  accountStatus: "active",
  kycVerified: true,
  accountType: "savings",
} as User;

export const transactionsData: Transaction[] = [
  {
    _id: "64a1b5c2a6d3f3e1a8c9d0f1",
    userId: {
      _id: "64a1b5d1a2b4c3d5e6f7a8c9",
      firstName: "John",
      lastName: "Doe",
      email: "johndoe@example.com",
      accountNumber: "123456789",
      balance: 1000.5,
      currency: "USD",
      role: "user",
      accountStatus: "active",
      kycVerified: true,
      accountType: "savings",
    },
    type: "deposit",
    amount: 15000.0,
    status: "approved",
    requiresCode: false,
    narration: "Payment for food",
    createdAt: new Date(),
    updatedAt: new Date(),
  } as unknown as Transaction,
  {
    _id: "64a1b5c3b7d4f3e2a8c9d0f2",
    userId: {
      _id: "64a1b5d1a2b4c3d5e6f7a8c9",
      firstName: "John",
      lastName: "Doe",
      email: "johndoe@example.com",
      accountNumber: "123456789",
      balance: 1000.5,
      currency: "USD",
      role: "user",
      accountStatus: "active",
      kycVerified: true,
      accountType: "savings",
    },
    type: "withdrawal",
    amount: 200.0,
    status: "pending",
    requiresCode: true,
    narration: "Payment for groceries",
    createdAt: new Date(),
    updatedAt: new Date(),
  } as unknown as Transaction,
  {
    _id: "64a1b5c4c8d5f3e3a8c9d0f3",
    userId: {
      _id: "64a1b5d1a2b4c3d5e6f7a8c9",
      firstName: "John",
      lastName: "Doe",
      email: "johndoe@example.com",
      accountNumber: "123456789",
      balance: 1000.5,
      currency: "USD",
      role: "user",
      accountStatus: "active",
      kycVerified: true,
      accountType: "savings",
    },
    type: "deposit",
    amount: 120.0,
    status: "approved",
    requiresCode: false,
    narration: "Payment for services",
    createdAt: new Date(),
    updatedAt: new Date(),
  } as unknown as Transaction,
  {
    _id: "64a1b5c5d9e6f3e4a8c9d0f4",
    userId: {
      _id: "64a1b5d1a2b4c3d5e6f7a8c9",
      firstName: "John",
      lastName: "Doe",
      email: "johndoe@example.com",
      accountNumber: "123456789",
      balance: 1000.5,
      currency: "USD",
      role: "user",
      accountStatus: "active",
      kycVerified: true,
      accountType: "savings",
    },
    type: "withdrawal",
    amount: 500.0,
    status: "approved",
    requiresCode: false,
    narration: "Payment for rent",
    createdAt: new Date(),
    updatedAt: new Date(),
  } as unknown as Transaction,
  {
    _id: "64a1b5c6eaf7f3e5a8c9d0f5",
    userId: {
      _id: "64a1b5d1a2b4c3d5e6f7a8c9",
      firstName: "John",
      lastName: "Doe",
      email: "johndoe@example.com",
      accountNumber: "123456789",
      balance: 1000.5,
      currency: "USD",
      role: "user",
      accountStatus: "active",
      kycVerified: true,
      accountType: "savings",
    },
    type: "deposit",
    amount: 300.0,
    status: "failed",
    requiresCode: true,
    narration: "Refund for shopping",
    createdAt: new Date(),
    updatedAt: new Date(),
  } as unknown as Transaction,
  {
    _id: "64a1b5c7fb08f3e6a8c9d0f6",
    userId: {
      _id: "64a1b5d1a2b4c3d5e6f7a8c9",
      firstName: "John",
      lastName: "Doe",
      email: "johndoe@example.com",
      accountNumber: "123456789",
      balance: 1000.5,
      currency: "USD",
      role: "user",
      accountStatus: "active",
      kycVerified: true,
      accountType: "savings",
    },
    type: "withdrawal",
    amount: 1000.0,
    status: "approved",
    requiresCode: false,
    narration: "Payment for office supplies",
    createdAt: new Date(),
    updatedAt: new Date(),
  } as unknown as Transaction,
] as Transaction[];

export const transactionStatusStyles = {
  approved: {
    borderColor: "border-blue-500",
    backgroundColor: "bg-blue-500",
    textColor: "text-green-500",
    chipBackgroundColor: "bg-lime-600", // Updated to a valid background color
  },
  pending: {
    borderColor: "border-yellow-600",
    backgroundColor: "bg-yellow-500",
    textColor: "text-yellow-700",
    chipBackgroundColor: "bg-yellow-100",
  },
  declined: {
    borderColor: "border-red-600",
    backgroundColor: "bg-red-500",
    textColor: "text-red-700",
    chipBackgroundColor: "bg-red-500",
  },
  failed: {
    borderColor: "border-gray-600",
    backgroundColor: "bg-gray-500",
    textColor: "text-gray-700",
    chipBackgroundColor: "bg-gray-100",
  },
  default: {
    borderColor: "border-gray-100",
    backgroundColor: "bg-gray-300",
    textColor: "text-gray-700",
    chipBackgroundColor: "bg-gray-100",
  },
};
