"use client";

import { Inter, IBM_Plex_Serif } from "next/font/google";
import "./globals.css";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import { ToasterProvider } from "@/context/toast/ToastContext";

import Toaster from "@/components/toaster/Toaster";

export const dynamic = "force-dynamic";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const ibmPlexSerif = IBM_Plex_Serif({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-ibm-plex-serif",
});

const queryClient = new QueryClient();

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${ibmPlexSerif.variable}`}>
        {/* React Query setup */}
        <QueryClientProvider client={queryClient}>
          {/* Toaster setup */}
          <ToasterProvider>
            <Toaster />
            {/* Render page content */}
            {children}
            {/* Devtools for react-query */}
            <ReactQueryDevtools initialIsOpen={false} />
          </ToasterProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
